### PR TITLE
Use `const` since local variable is never mutated

### PR DESCRIPTION
**Pull request by MadLittleMods**
Use `const` since local variable is never mutated

Spotted while trying this project out with the latest Zig `master` (`0.12.0-dev.1676+40b8c993f`)

```
src/main.zig:35:9: error: local variable is never mutated
    var rtn = try allocator.alloc(@TypeOf(data[0]), data.len);
        ^~~
src/main.zig:35:9: note: consider using 'const'
src/main.zig:45:9: error: local variable is never mutated
    var intermediate = try allocator.alloc(IdxT, data.len);
        ^~~~~~~~~~~~
src/main.zig:45:9: note: consider using 'const'
src/main.zig:43:9: error: local variable is never mutated
    var rtn = try allocator.alloc(@TypeOf(data[0]), data.len);
        ^~~
src/main.zig:43:9: note: consider using 'const'
src/main.zig:93:9: error: local variable is never mutated
    var data = try allocator.alloc(f64, 10000);
        ^~~~
src/main.zig:93:9: note: consider using 'const'
src/main.zig:92:9: error: local variable is never mutated
    var rand = ri.random();
        ^~~~
```

### Todo

 - [x] Wait for https://github.com/hmusgrave/zkwargs/pull/2 to be merged and update the `zkwargs` dependency in this project

### CODE REVIEW

File: build.zig.zon [hunk 1]
```diff
@@ -1,6 +1,9 @@
 .{
     .name = "zshuffle",
     .version = "0.0.0",
+    .paths = .{
+        ".",
+    },
```
Comment (MadLittleMods) [inline build.zig.zon]: This is a backwards-compatible change with Zig `0.11.0` but allows us to build with the latest Zig `master` (`0.12.0-dev.1676+40b8c993f`)

We could be more specific with which files to include but [`""` and `"."` is just a catch-all](https://github.com/ziglang/zig/blob/115ec25f2e4eed5033f34eaee8bf3477ff417ecc/src/Package/Fetch.zig#L1567-L1568) so everything is included like before ([more context](https://github.com/ziglang/zig/pull/17498)).

**Comment by hmusgrave** [comment]
Thanks for putting this together. Upstream zkwargs has your updates, and the README has the latest commit hash.

If you're using zshuffle actively, I should probably put together a commit to remove zkwargs as a dependency; it's overkill for the little bit of comptime specialization we're doing, and I think zshuffle would have slightly easier to understand code and less toil on your end if I made that weak.

File: build.zig.zon [hunk 2]
```diff
@@ -1,10 +1,13 @@
...
     .version = "0.0.0",
+    .paths = .{
+        "",
+    },
     .dependencies = .{
         .zkwargs = .{
-            .url = "https://github.com/hmusgrave/zkwargs/archive/4b23becf731ecaac1f29d629943d11b23c7802e8.tar.gz",
-            .hash = "1220f6fd467fd42cd5ec98a360caacdcda9d3b9c3557fdcdef285cabbdee3c7c79dc",
+            .url = "https://github.com/hmusgrave/zkwargs/archive/f73c42cedcfc14a84d44d8f79cfd92e3f60d2a31.tar.gz",
+            .hash = "1220398c2b04b8d5320a97868cc017776216f1910889b6b2413853044eb5d6057238",
```
Comment (MadLittleMods) [inline build.zig.zon:10]: > Thanks for putting this together. Upstream zkwargs has your updates, and the README has the latest commit hash.

Updated :white_check_mark:

File: build.zig.zon [hunk 3]
```diff
@@ -1,10 +1,13 @@
 .{
     .name = "zshuffle",
     .version = "0.0.0",
+    .paths = .{
+        "",
+    },
     .dependencies = .{
         .zkwargs = .{
```
Comment (MadLittleMods) [inline build.zig.zon:8]: > If you're using zshuffle actively, I should probably put together a commit to remove zkwargs as a dependency; it's overkill for the little bit of comptime specialization we're doing, and I think zshuffle would have slightly easier to understand code and less toil on your end if I made that tweak.

Sounds like a decent change. It's a bit of a faff to get everything going with all of the breaking changes as Zig evolves.

It has been a very good reference on how to manage dependencies/sub-dependencies in a project to base my own `build.zig` around though!

Comment (hmusgrave) [reply build.zig.zon:8]: The chance to see how the new package management worked was admittedly my motivation for linking the projects. I'll go ahead and approve this and let you know when I start on that update.

**Comment by MadLittleMods** [comment]
Thanks for the review and merge @hmusgrave 🐝
